language: node_js
node_js:
- 7
branches:
  only:
  - master
git:
  depth: 3
cache:
  directories:
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
before_script:
- git config --global user.name $GIT_EMAIL
- git config --global user.email $GIT_NAME
script:
- npm run deploy
env:
  global:
  - secure: Bv/ER4UIZQsFe/aszYGELWK0Y6T0J1OK0z+m8alsZqAHqdhA9nGXqfqrvn9fr/6qYwn1X/16giMGB6fkS3Fk5ShYOUAnPDQ4oF+DJKU0IrVwry3l7CVMLSrL5JHOGYS61xpR4BKdsB3X5R9h4wk+fxTbaCRhN81nIO+cqhbBGzt9NgWVUJTMBoaw0aBXO3WecQ95ayh5JOdjW3UkFZ8GrOY1ek52KMO5xb05D8VK6eK5M0nfElvDMNbVsyC0mVm3NXiT20E9jOBeLZJB50ECxh53mVgktFscO15SQD35EVw0lPOQISdALBre9LaAatVML6AVQz8LrBUzAFttxYzhZaM9c5XLrQr7J8ChHtzpl+6TwXRaMDEs9/SXeNZlnBLMZuiBjd3Ku6B1Ig6kleZUySr85b/Xa/vJ/xnNwBX5MjklYG7BiBI4CN+gAUvbhmChrRBuUobgcvTCoOdnzS4wIc+jap/5gg9Le8BdcpkO8UaY9rplo0qmqp6cdlek3rDFSBZkX904oVOxYS+ZwS73ap6EvpYRxlfVF7BSNOWKiBfQg0GEL3HNsK+2k8Nr4763DNzOxHgnMUdKD14TCXXb+TDj4uQ3JZw4QPamUKGv0KPAetJ2nF75Z/361bUrSS1xzRpGU0r2mlwG4mT7IN6gWoGxzmcZHLOTFuzunrkv/A4=
  - secure: hOz5wnRTjPvW37mgBaRGo0ARpY4w+hwn6fMPEYHG3oejUHxq62mxJ3BLq2gIpB8MJHrTG9X9mQXYypnNw/epnV7WolT8wnVQiPLCrLV7Pd32rDMTl8X8a61kcptO9fNvtjkRoc1wnBgJsm+SacB1p6jRrUGd7AoAxTsCyfyvRohn/5+n4Z+NVbYjmW/a/WPtvlNMm4HG7z1Di8WoGjdlVkd3+g5nwn/6crhqdyeBm4j1yj8cM2BObcy5TvUOEcsI5H1/WZ9FmHsUAxRKqod1WG18IpKt6HFOxiM8JuHMT42AhLs3xrq57Jaz+RJe2UgMy/ujLewJaJfQ6laK2GnDlzrreN2nzxM2YKHuim/h/8PZ1ZCUBkuU2L4l1SNhmsD+2wGVZMrie2hZVgc4VqK2xJOguD/L/FezZ+Sc4/ObIz1dpkrSdwhWazFNX2BwVeg4tlqPMIUfeNZNIoWMUJHDNX/ZswDs1ofrtyroUK+pDJjWa4fu1wuBuKFgK3LxjoCILnCGR8hcEwMAer2uzkE+o7gsoKmVkXQs7jBi+sGpRURf+sek9ZpUwLQq2s68CMsqjQdSMrQELlUT9zpmmGzxwS7W4vml/JfcqxnlGj8JkzHuRUyIJ9lCx352VUNsef60qgX55UkBZNtxewKLIiQkUVak0Vm+Zdtq8+y5nBf7FnM=
  - secure: mlzR8M8cJQ3ie5tPjYRX6PwFxCfqiWdkFIB4mu081tPlRqwR8pQ53/NseJ6Uu8fBJJ6mziy+9Ac9npTmjlwoYMGExt8wJYpiHyggwD3YFro8iDmufmmcGy5YG8EiQCuQ15uBRIAU/XktInNlaQaVdRTs3FZxToK+iYalCGUBS9D1Fbe9Yr9oZ0EY9F/Z1Y2tW+qXoW9e+RVE3FqBywKDchZ/6rQoeK2Mo17zB645tuzw/JM++DdpexxyThyEJcjfh6PqOJMfK8B7KfrLiIrYi0f0DYnf0t2YsBi39QOBpcfCheizIbKPm2hXFk90GR6eDnvypejUyuMhgqWe3m2O/zbKqQ7DF4hNDHQlazlIQqL/fAupArUyumeXEdNpLUqi6wx3j62TgRDSIwQmZ6e0AlAiOT/2ZvR4pUHMh+9Di68tnTNHroQ5tiwgy585KE+K9k33NR74k0gpmgzbnSQMeVsTG6spX/9sgcdATVr1jCpJ6d0EckleJE8CCgUe2VX4x7uqJsRhiYRrYGmW0KhaqT3bbHguGPYH0gwzvPDn8D1IMAhtqeQCCMGC2i03g7y6XaksAvVP1EYhYlYHzsYHQyWmiU/RYKrRKhhocIlSAHhmAUN5HxmxjhdXm071qaCt27aiSJXii9mEvjxVoyy03S0MglHQa4LYLsklTJ27fwE=
notifications:
  slack:
    rooms:
    - secure: PU1Da3FBb2zFQaROM2izTFz53gllw2cl+QcuwHndA3Sxh2pYojGk3NuQ4F5K+IC0foSF9gPMh9pocMQ/ajpYCxCIjjs8M8o2yGeM3dFZK8Xa8YeKbkyjXTGWjvDgZOGNXXqyuaALZBnkZJhce9btaJhwQFj2aDSvVcZWb1PeRnUyHJY6fLuKV0vW6GDArQri7KSalHz4fXbpm/cv1jOeO/PBhl09MNQY2x3X4Jd7u+/6Q07sucJWnuvWubv0gT6WqfU5GbtlFnyiiYFYdlnxACQo+kRwMwQFYI4BJl6QX8oTDzTg/B/l/MbVEoYjPzApwS38lIBRc6qJ0lPyjTc7dmML1yiL+sSJJC8QbFeQBYJYnUzWQzlhhp0MeIFDOa9D1+gHnHRJQqN8jqpbyF25DNgWu+Tp+7/uJQw/TFqiIykC4gRg6NtxVN7sCews/ksLolpqU0ebyDbBai1qo2JSNN5niLJS/4UUPdZuSYsHXNLiiCOzpyPJsTss6Mdy3QjS6P7zSBJDkcX1bWzTPk7OTtN0jSq/BR7Vg5pmFshaFSYxRoWeF8ekQ9wG7LRNWRuMxRNQdEzXkbf+b26+BzV7E2AHzrjF8yAwA/KjQEFKwFqbWuNLkqfqWGIJ4s1xn8hq6SBeOveklGWpERDx92tLrRruRuKSE6+bYntn3LNfwA0=
