language: node_js
node_js:
  - 7
# safelist
branches:
  only:
  - master
git:
  depth: 3
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
before_script:
  - npm install
script:
  - npm build
