language: node_js
node_js:
  - 7
branches:
  only:
    - master
git:
  depth: 3
cache:
  directories:
    - packages/create-react-app/node_modules
    - packages/react-scripts/node_modules
before_script:
  - 'git config --global user.name $GIT_EMAIL'
  - 'git config --global user.email $GIT_NAME'
script:
  - npm run deploy
env:
  global:
    - secure: >-
        Bv/ER4UIZQsFe/aszYGELWK0Y6T0J1OK0z+m8alsZqAHqdhA9nGXqfqrvn9fr/6qYwn1X/16giMGB6fkS3Fk5ShYOUAnPDQ4oF+DJKU0IrVwry3l7CVMLSrL5JHOGYS61xpR4BKdsB3X5R9h4wk+fxTbaCRhN81nIO+cqhbBGzt9NgWVUJTMBoaw0aBXO3WecQ95ayh5JOdjW3UkFZ8GrOY1ek52KMO5xb05D8VK6eK5M0nfElvDMNbVsyC0mVm3NXiT20E9jOBeLZJB50ECxh53mVgktFscO15SQD35EVw0lPOQISdALBre9LaAatVML6AVQz8LrBUzAFttxYzhZaM9c5XLrQr7J8ChHtzpl+6TwXRaMDEs9/SXeNZlnBLMZuiBjd3Ku6B1Ig6kleZUySr85b/Xa/vJ/xnNwBX5MjklYG7BiBI4CN+gAUvbhmChrRBuUobgcvTCoOdnzS4wIc+jap/5gg9Le8BdcpkO8UaY9rplo0qmqp6cdlek3rDFSBZkX904oVOxYS+ZwS73ap6EvpYRxlfVF7BSNOWKiBfQg0GEL3HNsK+2k8Nr4763DNzOxHgnMUdKD14TCXXb+TDj4uQ3JZw4QPamUKGv0KPAetJ2nF75Z/361bUrSS1xzRpGU0r2mlwG4mT7IN6gWoGxzmcZHLOTFuzunrkv/A4=
    - secure: >-
        hOz5wnRTjPvW37mgBaRGo0ARpY4w+hwn6fMPEYHG3oejUHxq62mxJ3BLq2gIpB8MJHrTG9X9mQXYypnNw/epnV7WolT8wnVQiPLCrLV7Pd32rDMTl8X8a61kcptO9fNvtjkRoc1wnBgJsm+SacB1p6jRrUGd7AoAxTsCyfyvRohn/5+n4Z+NVbYjmW/a/WPtvlNMm4HG7z1Di8WoGjdlVkd3+g5nwn/6crhqdyeBm4j1yj8cM2BObcy5TvUOEcsI5H1/WZ9FmHsUAxRKqod1WG18IpKt6HFOxiM8JuHMT42AhLs3xrq57Jaz+RJe2UgMy/ujLewJaJfQ6laK2GnDlzrreN2nzxM2YKHuim/h/8PZ1ZCUBkuU2L4l1SNhmsD+2wGVZMrie2hZVgc4VqK2xJOguD/L/FezZ+Sc4/ObIz1dpkrSdwhWazFNX2BwVeg4tlqPMIUfeNZNIoWMUJHDNX/ZswDs1ofrtyroUK+pDJjWa4fu1wuBuKFgK3LxjoCILnCGR8hcEwMAer2uzkE+o7gsoKmVkXQs7jBi+sGpRURf+sek9ZpUwLQq2s68CMsqjQdSMrQELlUT9zpmmGzxwS7W4vml/JfcqxnlGj8JkzHuRUyIJ9lCx352VUNsef60qgX55UkBZNtxewKLIiQkUVak0Vm+Zdtq8+y5nBf7FnM=
    - secure: >-
        XbKvT61ORi84dM6jXVvMA9Pk/I9NP0avmkWzPa863I3MB65orgXyjTJzgHUjDE7TQEyfNxSCE/iql7oXz7bPISUMzA0E3kBqKlxw5FJtrYEJFy0Ktd4KxPzK4A9m52+ww2Bf/Syk5Llr1dVCq/UZj2rvZmatTkTE/RX5RI6hwGiZErhWZW/xTCr6u/RMtHD5ZsVESyNAKF+9m2CKtNuZPTtDGB3dRV1ZhVbJ4+CQJ1Xm9vlC1NrOf77LXtVNFqc+Z6pUN4hZ0SpG85li9yioBYmHmfyT1iFLsXkBeIigBPy1oUWknVoJ4BgLTSbGxQE3DcgBQ+pICaWYsssxpVa70Mm85LaktP73wZ7GGL1+WLIQqnMIpFI6deUI2UIHHwSjUhjB6JQdEsEyQHZosQXn/f5Kh87v4sWteCuUyMIvSMg20w71QAuHFZduRBc+QaaEvQnsI3l7KPI40OZZKq/nahZ6Fn67DawV5z+iykZZvc7JHdpmThydZ5Kj3n0t2QrZV+lKb5/YEdR8UfmTPEe3s1qUCePIzMOY/a+gvkODfVs29cBz7cRE/UOa0jpH3wbaL5pwCRV7hwoNIPtVSU+scIJNLGhhGvKzedRhbPO3t0r952ZlEGX2msVzArBfP7//pXQ6HDfsxLReapMiBuQFNkTF76pxNIJCCjEMueMd8hY=
